### This file acts as the global config across the website.
### Any variables in this file can be accessed in other files using
###    `{{ site.variable }}`


######################
# Site configuration #
######################
# This title will display across the website
title: "Civil Service LGBT+ Network"
# This description is predominantly for Search Engine Optimisation
description: "The Civil Service LGBT+ Network helps to create a more diverse, inclusive and equal place to work for lesbian, gay, bisexual and trans civil servants."
# Instead of "author", have the organisation name as the default
author: "Civil Service LGBT+ Network"
organisation: "Civil Service LGBT+ Network"
email: "info@civilservice.lgbt"

baseurl: "/images" # the subpath of your site, e.g. /blog
url: "https://www.civilservice.lgbt"

github-repo: "https://github.com/civilservicelgbt/images/"

#########################
# Social media accounts #
#########################
social-media-accounts:
  - account: "Facebook"
    url: "//facebook.com/civilservicelgbt"
    display-text: "Like us on Facebook"
    alt-text: "Visit our Facebook profile page"
    handle: "civilservicelgbt" # Automatically pre-pends http://facebook.com/
    hidden: false
  - account: "Twitter"
    url: "//twitter.com/cslgbt" # Twitter handle i.e. joebloggs
    display-text: "Follow us on Twitter"
    alt-text: "Visit our Twitter profile page"
    handle: "cslgbt" # Twitter handle i.e. joebloggs
    hidden: false
  - account: "Flickr"
    url:  "//www.flickr.com/photos/civilservicelgbt/"
    display-text: "Find us on Flickr"
    alt-text: "Visit our Flickr profile page"
    handle:  "civilservicelgbt"
    hidden: false
  - account: "Instagram"
    url:  "//www.instagram.com/civilservicelgbt"
    display-text: "Follow us on Instagram"
    alt-text: "Visit our Instagram profile page"
    handle:  "civilservicelgbt"
    hidden: false
  - account: "Youtube"
    url: "//youtube.com/"
    display-text: "Subscribe to us on Youtube"
    alt-text: "Visit our Youtube profile page"
    handle: ""
    hidden: true

###################
# Header settings #
###################
# This title will show in the main menu bar
header-menu--title--display-text: "Civil Service LGBT+"
# If this theme is being used for a subdomain (i.e. blog.civilservice.lgbt) then set
# - `header-menu--subdomain-title` to 'true'
# - `header-menu--subdomain-title--display-text` to any string value (i.e. "Image maker")
header-menu--subdomain-title: true
header-menu--subdomain-title--display-text: Admin 

# Header menu links
header-menu--links--hidden: true
header-menu--links:
  - display-text: "Home"
    alt-text: "Visit the home page"
    url: "/"
    hidden: true

###################
# Footer settings #
###################
# This title will show in the main menu bar
footer--title--display-text: "Civil Service LGBT+ Network"

# This text will be displayed at the bottom of the website.
footer--production-notice: "Website created by <a href='//www.johnpe.art' title='Visit John Peartâ€™s website (Opens in new window)' target='_blank' rel='noopener noreferrer'>John Peart</a>."
footer--copyright-notice: "All content is released under the <a href='https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/' title='Read more about the Open Government License. (Opens in new window)' target='_blank'>Open Government License</a> unless otherwise stated. Please attribute our work."

# Footer menu links
footer-menu--links:
  - display-text: "Home"
    alt-text: "Visit the home page"
    url: "/"
    hidden: true

# Toggle home page blocks
home-news:			false
home-events:		false
home-publications:	false
home-consultations:	false
home-topics:		false


###############
# Asset paths #
###############
# General paths
image-path: "/assets/images"
css-path: "/assets/styles"
js-path: "/assets/scripts"

# Favicons and social graph
social-media-image: "/assets/images/site/social-media.png"
favicon: "/favicon.ico"
favicon-svg: "/assets/images/site/favicon.svg"
favicon-pinned-svg: "/assets/images/site/favicon-pinned-svg.svg"
favicon-large-png: "/assets/images/site/favicon-large-png.png"
theme-colour: "#e6007e"



##################################
# Analytics and domain ownership #
##################################
# Google settings
google-site-verification: "RA-YBjxyRYVSuSFAYLKkufs6gjme6kMcihoB2KgKrTA"
google-analytics: "UA-47423042-2" # GA ID code
google-analytics-domain: ".www.civilservice.lgbt"

###############
# Collections #
###############
#This is the default permalink for the "_posts" folder.
permalink: /:year/:month/:day/:title:output_ext 

collections:
  pages:
    output: true
    permalink: /:path/
    defaults:
      values:
        layout: page

defaults:
  - scope:
      path: "images"
    values:
      image: true
        
##################
# Build settings #
##################
remote_theme: civilservicelgbt/theme
permalink: pretty
markdown: kramdown
future: false
highlighter: rouge
sass:
  sass_dir: _sass

plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-feed
- jekyll-redirect-from

    
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/