name: Build and deploy site

# UNCOMMENT THE BELOW BLOCK BASED ON NEED
# USE 'PUSH' IF YOU WANT THE SITE TO BUILD WHEN YOU ADD FILES
# USE 'SCHEDULE' IF YOU WANT TO RUN DAILY (OR ANOTHER DEFINED 'CRON' PERIOD)
on:
  push:
    branches:
      - main
#   schedule:
#     - cron: "0 0 * * *"

jobs:
  jekyll:
    runs-on: ubuntu-16.04 # can change this to ubuntu-latest if you prefer
    steps:
      - name: ðŸ“‚ setup
        uses: actions/checkout@v2

      - name: ðŸ’Ž setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7 # can change this to 2.7 or whatever version you prefer

      - name: ðŸ”¨ install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true

      - name: ðŸš€ deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.JEKYLL_BUILD_SECRET }}
          # you will need to create a key and add it to the repo's secrets to make this work
          publish_dir: ./_site
          # if the repo you are deploying to is <username>.github.io, uncomment the line below.
          # if you are including the line below, make sure your source files are NOT in the master branch:
          # publish_branch: gh-pages